# Site Settings
title: Puneeth Rao Dilip
description: My Portfolio 
url: "https://puneethrao.github.io"

# Theme
theme: jekyll-theme-cayman
# Build settings
markdown: kramdown

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
