# Site Settings
title:   Puneeth Rao Dilip

url: "https://puneethrao.github.io"

# Theme
theme: jekyll-theme-midnight
# Build settings
markdown: kramdown

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
